In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.backends.backend_pdf
import matplotlib as mpl
import copy
from matplotlib.colors import LinearSegmentedColormap, ListedColormap

In [2]:
tanscripts_read= "/home/androx/Documents/trabalho/datasets/Disease_genes/mane/Homo_sapiens.GRCh38.112.chr.gff3"
tanscripts_df = pd.read_csv(tanscripts_read, sep="\t", header=None)

tanscripts_df

0       1                  2           3            4        5  6  7  \
0        1  GRCh38         chromosome         1.0  248956422.0        .  .  .   
1        1       .  biological_region     10469.0      11240.0  1.3e+03  .  .   
2        1       .  biological_region     10650.0      10657.0    0.999  +  .   
3        1       .  biological_region     10655.0      10657.0    0.999  -  .   
4        1       .  biological_region     10678.0      10687.0    0.999  +  .   
...     ..     ...                ...         ...          ...      ... .. ..   
3516515  Y       .  biological_region  57215804.0   57215813.0    0.999  -  .   
3516516  Y       .  biological_region  57215832.0   57215840.0    0.999  +  .   
3516517  Y       .  biological_region  57215833.0   57215842.0    0.999  -  .   
3516518  Y       .  biological_region  57215862.0   57215867.0    0.999  +  .   
3516519  Y       .  biological_region  57215862.0   57215870.0    0.999  -  .   

                                                         8  
0        ID=chromosome:1;Alias=CM000663.2,chr1,NC_00000...  
1                 external_name=oe %3D 0.79;logic_name=cpg  
2                                       logic_name=eponine  
3                                       logic_name=eponine  
4                                       logic_name=eponine  
...                                                    ...  
3516515                                 logic_name=eponine  
3516516                                 logic_name=eponine  
3516517                                 logic_name=eponine  
3516518                                 logic_name=eponine  
3516519                                 logic_name=eponine  

[3516520 rows x 9 columns]

In [3]:
tanscripts_df = tanscripts_df.rename(columns={0: 'Chr', 1: 'Genome', 2: 'Type', 3: 'First_index', 4: 'Last_index', 5: 'Value', 6: 'Unknown1', 7: 'Unknown2', 8: 'Identifiers'})
tanscripts_df

Chr  Genome               Type  First_index   Last_index    Value  \
0         1  GRCh38         chromosome          1.0  248956422.0        .   
1         1       .  biological_region      10469.0      11240.0  1.3e+03   
2         1       .  biological_region      10650.0      10657.0    0.999   
3         1       .  biological_region      10655.0      10657.0    0.999   
4         1       .  biological_region      10678.0      10687.0    0.999   
...      ..     ...                ...          ...          ...      ...   
3516515   Y       .  biological_region   57215804.0   57215813.0    0.999   
3516516   Y       .  biological_region   57215832.0   57215840.0    0.999   
3516517   Y       .  biological_region   57215833.0   57215842.0    0.999   
3516518   Y       .  biological_region   57215862.0   57215867.0    0.999   
3516519   Y       .  biological_region   57215862.0   57215870.0    0.999   

        Unknown1 Unknown2                                        Identifiers  
0              .        .  ID=chromosome:1;Alias=CM000663.2,chr1,NC_00000...  
1              .        .           external_name=oe %3D 0.79;logic_name=cpg  
2              +        .                                 logic_name=eponine  
3              -        .                                 logic_name=eponine  
4              +        .                                 logic_name=eponine  
...          ...      ...                                                ...  
3516515        -        .                                 logic_name=eponine  
3516516        +        .                                 logic_name=eponine  
3516517        -        .                                 logic_name=eponine  
3516518        +        .                                 logic_name=eponine  
3516519        -        .                                 logic_name=eponine  

[3516520 rows x 9 columns]

In [4]:
tanscripts_df['Type'].unique()

array(['chromosome', 'biological_region', 'ncRNA_gene', 'lnc_RNA', 'exon',
       nan, 'pseudogene', 'pseudogenic_transcript', 'miRNA', 'gene',
       'mRNA', 'five_prime_UTR', 'CDS', 'three_prime_UTR', 'snRNA',
       'transcript', 'unconfirmed_transcript', 'snoRNA', 'scRNA', 'rRNA',
       'processed_transcript', 'V_gene_segment', 'D_gene_segment',
       'J_gene_segment', 'C_gene_segment', 'tRNA'], dtype=object)

In [5]:
chromosmes = tanscripts_df.loc[tanscripts_df['Type'] == "chromosome"]
chromosmes

Chr  Genome        Type  First_index   Last_index Value Unknown1  \
0         1  GRCh38  chromosome          1.0  248956422.0     .        .   
328201   10  GRCh38  chromosome          1.0  133797422.0     .        .   
467767   11  GRCh38  chromosome          1.0  135086622.0     .        .   
673000   12  GRCh38  chromosome          1.0  133275309.0     .        .   
862634   13  GRCh38  chromosome          1.0  114364328.0     .        .   
924501   14  GRCh38  chromosome          1.0  107043718.0     .        .   
1048326  15  GRCh38  chromosome          1.0  101991189.0     .        .   
1171301  16  GRCh38  chromosome          1.0   90338345.0     .        .   
1329042  17  GRCh38  chromosome          1.0   83257441.0     .        .   
1536644  18  GRCh38  chromosome          1.0   80373285.0     .        .   
1598313  19  GRCh38  chromosome          1.0   58617616.0     .        .   
1791801   2  GRCh38  chromosome          1.0  242193529.0     .        .   
2063156  20  GRCh38  chromosome          1.0   64444167.0     .        .   
2145930  21  GRCh38  chromosome          1.0   46709983.0     .        .   
2186784  22  GRCh38  chromosome          1.0   50818468.0     .        .   
2261287   3  GRCh38  chromosome          1.0  198295559.0     .        .   
2484781   4  GRCh38  chromosome          1.0  190214555.0     .        .   
2628956   5  GRCh38  chromosome          1.0  181538259.0     .        .   
2786252   6  GRCh38  chromosome          1.0  170805979.0     .        .   
2952608   7  GRCh38  chromosome          1.0  159345973.0     .        .   
3120542   8  GRCh38  chromosome          1.0  145138636.0     .        .   
3248106   9  GRCh38  chromosome          1.0  138394717.0     .        .   
3384196  MT  GRCh38  chromosome          1.0      16569.0     .        .   
3384360   X  GRCh38  chromosome          1.0  156040895.0     .        .   
3505822   Y  GRCh38  chromosome          1.0   57227415.0     .        .   

        Unknown2                                        Identifiers  
0              .  ID=chromosome:1;Alias=CM000663.2,chr1,NC_00000...  
328201         .  ID=chromosome:10;Alias=CM000672.2,chr10,NC_000...  
467767         .  ID=chromosome:11;Alias=CM000673.2,chr11,NC_000...  
673000         .  ID=chromosome:12;Alias=CM000674.2,chr12,NC_000...  
862634         .  ID=chromosome:13;Alias=CM000675.2,chr13,NC_000...  
924501         .  ID=chromosome:14;Alias=CM000676.2,chr14,NC_000...  
1048326        .  ID=chromosome:15;Alias=CM000677.2,chr15,NC_000...  
1171301        .  ID=chromosome:16;Alias=CM000678.2,chr16,NC_000...  
1329042        .  ID=chromosome:17;Alias=CM000679.2,chr17,NC_000...  
1536644        .  ID=chromosome:18;Alias=CM000680.2,chr18,NC_000...  
1598313        .  ID=chromosome:19;Alias=CM000681.2,chr19,NC_000...  
1791801        .  ID=chromosome:2;Alias=CM000664.2,chr2,NC_00000...  
2063156        .  ID=chromosome:20;Alias=CM000682.2,chr20,NC_000...  
2145930        .  ID=chromosome:21;Alias=CM000683.2,chr21,NC_000...  
2186784        .  ID=chromosome:22;Alias=CM000684.2,chr22,NC_000...  
2261287        .  ID=chromosome:3;Alias=CM000665.2,chr3,NC_00000...  
2484781        .  ID=chromosome:4;Alias=CM000666.2,chr4,NC_00000...  
2628956        .  ID=chromosome:5;Alias=CM000667.2,chr5,NC_00000...  
2786252        .  ID=chromosome:6;Alias=CM000668.2,chr6,NC_00000...  
2952608        .  ID=chromosome:7;Alias=CM000669.2,chr7,NC_00000...  
3120542        .  ID=chromosome:8;Alias=CM000670.2,chr8,NC_00000...  
3248106        .  ID=chromosome:9;Alias=CM000671.2,chr9,NC_00000...  
3384196        .   ID=chromosome:MT;Alias=chrM,J01415.2,NC_012920.1  
3384360        .  ID=chromosome:X;Alias=CM000685.2,chrX,NC_00002...  
3505822        .  ID=chromosome:Y;Alias=CM000686.2,chrY,NC_00002...

In [6]:
genes = tanscripts_df.loc[tanscripts_df['Type'] == "gene"]
genes

Chr          Genome  Type  First_index  Last_index Value Unknown1  \
93        1  ensembl_havana  gene      65419.0     71585.0     .        +   
395       1  ensembl_havana  gene     450740.0    451678.0     .        -   
541       1  ensembl_havana  gene     685716.0    686654.0     .        -   
1161      1  ensembl_havana  gene     923923.0    944575.0     .        +   
1524      1  ensembl_havana  gene     944203.0    959309.0     .        -   
...      ..             ...   ...          ...         ...   ...      ...   
3515710   Y  ensembl_havana  gene   25030901.0  25062548.0     .        -   
3515921   Y  ensembl_havana  gene   25622117.0  25624902.0     .        +   
3516228   Y  ensembl_havana  gene   57067865.0  57130289.0     .        +   
3516327   Y  ensembl_havana  gene   57184216.0  57197337.0     .        +   
3516392   Y  ensembl_havana  gene   57207346.0  57212230.0     .        +   

        Unknown2                                        Identifiers  
93             .  ID=gene:ENSG00000186092;Name=OR4F5;biotype=pro...  
395            .  ID=gene:ENSG00000284733;Name=OR4F29;biotype=pr...  
541            .  ID=gene:ENSG00000284662;Name=OR4F16;biotype=pr...  
1161           .  ID=gene:ENSG00000187634;Name=SAMD11;biotype=pr...  
1524           .  ID=gene:ENSG00000188976;Name=NOC2L;biotype=pro...  
...          ...                                                ...  
3515710        .  ID=gene:ENSG00000185894;Name=BPY2C;biotype=pro...  
3515921        .  ID=gene:ENSG00000172288;Name=CDY1;biotype=prot...  
3516228        .  ID=gene:ENSG00000292366;Name=VAMP7;biotype=pro...  
3516327        .  ID=gene:ENSG00000292373;Name=IL9R;biotype=prot...  
3516392        .  ID=gene:ENSG00000292372;Name=WASH6P;biotype=pr...  

[21547 rows x 9 columns]

In [7]:
genes["Identifiers"]

93         ID=gene:ENSG00000186092;Name=OR4F5;biotype=pro...
395        ID=gene:ENSG00000284733;Name=OR4F29;biotype=pr...
541        ID=gene:ENSG00000284662;Name=OR4F16;biotype=pr...
1161       ID=gene:ENSG00000187634;Name=SAMD11;biotype=pr...
1524       ID=gene:ENSG00000188976;Name=NOC2L;biotype=pro...
                                 ...                        
3515710    ID=gene:ENSG00000185894;Name=BPY2C;biotype=pro...
3515921    ID=gene:ENSG00000172288;Name=CDY1;biotype=prot...
3516228    ID=gene:ENSG00000292366;Name=VAMP7;biotype=pro...
3516327    ID=gene:ENSG00000292373;Name=IL9R;biotype=prot...
3516392    ID=gene:ENSG00000292372;Name=WASH6P;biotype=pr...
Name: Identifiers, Length: 21547, dtype: object

In [8]:
CDSs = tanscripts_df.loc[tanscripts_df['Type'] == "CDS"]
CDSs

Chr          Genome Type  First_index  Last_index Value Unknown1  \
99        1          havana  CDS      65565.0     65573.0     .        +   
100       1          havana  CDS      69037.0     70008.0     .        +   
398       1  ensembl_havana  CDS     450740.0    451678.0     .        -   
544       1  ensembl_havana  CDS     685716.0    686654.0     .        -   
1165      1          havana  CDS     924432.0    924948.0     .        +   
...      ..             ...  ...          ...         ...   ...      ...   
3516411   Y          havana  CDS   57209532.0  57209733.0     .        +   
3516413   Y          havana  CDS   57209822.0  57209980.0     .        +   
3516415   Y          havana  CDS   57210640.0  57210792.0     .        +   
3516417   Y          havana  CDS   57211552.0  57211620.0     .        +   
3516419   Y          havana  CDS   57211761.0  57211894.0     .        +   

        Unknown2                                        Identifiers  
99             0  ID=CDS:ENSP00000493376;Parent=transcript:ENST0...  
100            0  ID=CDS:ENSP00000493376;Parent=transcript:ENST0...  
398            0  ID=CDS:ENSP00000409316;Parent=transcript:ENST0...  
544            0  ID=CDS:ENSP00000329982;Parent=transcript:ENST0...  
1165           0  ID=CDS:ENSP00000478421;Parent=transcript:ENST0...  
...          ...                                                ...  
3516411        0  ID=CDS:ENSP00000518618;Parent=transcript:ENST0...  
3516413        2  ID=CDS:ENSP00000518618;Parent=transcript:ENST0...  
3516415        2  ID=CDS:ENSP00000518618;Parent=transcript:ENST0...  
3516417        2  ID=CDS:ENSP00000518618;Parent=transcript:ENST0...  
3516419        2  ID=CDS:ENSP00000518618;Parent=transcript:ENST0...  

[900145 rows x 9 columns]

In [9]:
exons = tanscripts_df.loc[tanscripts_df['Type'] == "exon"]
exons

Chr  Genome  Type  First_index  Last_index Value Unknown1 Unknown2  \
18        1  havana  exon      11869.0     12227.0     .        +        .   
19        1  havana  exon      12613.0     12721.0     .        +        .   
20        1  havana  exon      13221.0     14409.0     .        +        .   
24        1  havana  exon      12010.0     12057.0     .        +        .   
25        1  havana  exon      12179.0     12227.0     .        +        .   
...      ..     ...   ...          ...         ...   ...      ...      ...   
3516493   Y  havana  exon   57212184.0  57213125.0     .        -        .   
3516494   Y  havana  exon   57213204.0  57213357.0     .        -        .   
3516495   Y  havana  exon   57213526.0  57213602.0     .        -        .   
3516496   Y  havana  exon   57213880.0  57213964.0     .        -        .   
3516497   Y  havana  exon   57214350.0  57214397.0     .        -        .   

                                               Identifiers  
18       Parent=transcript:ENST00000456328;Name=ENSE000...  
19       Parent=transcript:ENST00000456328;Name=ENSE000...  
20       Parent=transcript:ENST00000456328;Name=ENSE000...  
24       Parent=transcript:ENST00000450305;Name=ENSE000...  
25       Parent=transcript:ENST00000450305;Name=ENSE000...  
...                                                    ...  
3516493  Parent=transcript:ENST00000711270;Name=ENSE000...  
3516494  Parent=transcript:ENST00000711270;Name=ENSE000...  
3516495  Parent=transcript:ENST00000711270;Name=ENSE000...  
3516496  Parent=transcript:ENST00000711270;Name=ENSE000...  
3516497  Parent=transcript:ENST00000711270;Name=ENSE000...  

[1668627 rows x 9 columns]

In [10]:
regions = tanscripts_df.loc[tanscripts_df['Type'] == "biological_region"]
regions

Chr Genome               Type  First_index  Last_index    Value  \
1         1      .  biological_region      10469.0     11240.0  1.3e+03   
2         1      .  biological_region      10650.0     10657.0    0.999   
3         1      .  biological_region      10655.0     10657.0    0.999   
4         1      .  biological_region      10678.0     10687.0    0.999   
5         1      .  biological_region      10681.0     10688.0    0.999   
...      ..    ...                ...          ...         ...      ...   
3516515   Y      .  biological_region   57215804.0  57215813.0    0.999   
3516516   Y      .  biological_region   57215832.0  57215840.0    0.999   
3516517   Y      .  biological_region   57215833.0  57215842.0    0.999   
3516518   Y      .  biological_region   57215862.0  57215867.0    0.999   
3516519   Y      .  biological_region   57215862.0  57215870.0    0.999   

        Unknown1 Unknown2                               Identifiers  
1              .        .  external_name=oe %3D 0.79;logic_name=cpg  
2              +        .                        logic_name=eponine  
3              -        .                        logic_name=eponine  
4              +        .                        logic_name=eponine  
5              -        .                        logic_name=eponine  
...          ...      ...                                       ...  
3516515        -        .                        logic_name=eponine  
3516516        +        .                        logic_name=eponine  
3516517        -        .                        logic_name=eponine  
3516518        +        .                        logic_name=eponine  
3516519        -        .                        logic_name=eponine  

[180392 rows x 9 columns]

In [11]:
tanscripts_df = None

In [12]:
# Nao é util para já agregar todos od conjuntos, mais apropriado fazer um mapa de cada coisa

def calc_exons_introns(chromosomes_df, sequence_df, exons_df, genes_df, regions_df):
    """interval_df = Genes or CDSs
    +2⁰ = 1: is exon
    +2¹ = 2: is part of a region
    +2² = 4: is part of CDS
    +2³ = 8: is part of gene
    """
    Chrmosomes_matrix = []
    for line in chromosomes_df.index:
        chromosome = chromosomes_df["Chr"][line]
        print("searching citobands in chromossome: ", chromosome)
        chr_size = int(chromosomes_df["Last_index"][line])
        chromosome_elements = sequence_df.loc[sequence_df['Chr'] == chromosome]
        chromosome_exons = exons_df.loc[exons_df['Chr'] == chromosome]
        chr_genes = genes_df.loc[genes_df['Chr'] == chromosome]
        chr_regions = regions_df.loc[regions_df['Chr'] == chromosome]
        element_introns = np.zeros((chr_size), dtype=int)
        #genes region
        for row in chr_genes.index:
            for i in range (int(chr_genes["First_index"][row]), int(chr_genes["Last_index"][row])):
                element_introns[i]+=8
        #CDS region
        for row in chromosome_elements.index:
            for i in range (int(chromosome_elements["First_index"][row]), int(chromosome_elements["Last_index"][row])):
                element_introns[i]+=4
        #other regions
        for row in chr_regions.index:
            for i in range (int(chr_regions["First_index"][row]), int(chr_regions["Last_index"][row])):
                element_introns[i]+=2
        #exons region
        for row in chromosome_exons.index:
            for i in range (int(chromosome_exons["First_index"][row]), int(chromosome_exons["Last_index"][row])):
                element_introns[i]+=1
        
        Chrmosomes_matrix.append(element_introns)
    return Chrmosomes_matrix


In [13]:
def element_matrix(chromosomes_df, sequence_df):
    """
    sequence_df = Genes or CDSs, exons or other_regions
    """
    Chromosomes_matrix = []
    for line in chromosomes_df.index:
        chromosome = chromosomes_df["Chr"][line]
        print("searching citobands in chromossome: ", chromosome)
        chr_size = int(chromosomes_df["Last_index"][line])
        chr_sequence = sequence_df.loc[sequence_df['Chr'] == chromosome]
        chr_array = np.zeros((chr_size), dtype=int)
        #elements region
        for row in chr_sequence.index:
            for i in range (int(chr_sequence["First_index"][row]), int(chr_sequence["Last_index"][row])):
                chr_array[i]+=1
        
        Chromosomes_matrix.append(chr_array)
    return Chromosomes_matrix

In [14]:
def introns_exons_matrix(chromosomes_df, CDS_df, exons_df):
    """
    sequence_df = Genes or CDSs, exons or other_regions
    if CDS element: +2
    if exon: +1
    introns = 2
    exons = 3
    """
    Chromosomes_matrix = []
    for line in chromosomes_df.index:
        chromosome = chromosomes_df["Chr"][line]
        print("searching citobands in chromossome: ", chromosome)
        chr_size = int(chromosomes_df["Last_index"][line])
        chr_CDS = CDS_df.loc[CDS_df['Chr'] == chromosome]
        chromosome_exons = exons_df.loc[exons_df['Chr'] == chromosome]
        chr_array = np.zeros((chr_size), dtype=int)
        #elements region
        #CDS region
        for row in chr_CDS.index:
            for i in range (int(chr_CDS["First_index"][row]), int(chr_CDS["Last_index"][row])):
                chr_array[i]+=2
        #exons region
        for row in chromosome_exons.index:
            for i in range (int(chromosome_exons["First_index"][row]), int(chromosome_exons["Last_index"][row])):
                chr_array[i]+=1
        
        Chromosomes_matrix.append(chr_array)
    return Chromosomes_matrix

In [15]:
exons_matrix = element_matrix(chromosmes, exons)
exons_matrix

searching citobands in chromossome:  1
searching citobands in chromossome:  10
searching citobands in chromossome:  11
searching citobands in chromossome:  12
searching citobands in chromossome:  13
searching citobands in chromossome:  14
searching citobands in chromossome:  15
searching citobands in chromossome:  16
searching citobands in chromossome:  17
searching citobands in chromossome:  18
searching citobands in chromossome:  19
searching citobands in chromossome:  2
searching citobands in chromossome:  20
searching citobands in chromossome:  21
searching citobands in chromossome:  22
searching citobands in chromossome:  3
searching citobands in chromossome:  4
searching citobands in chromossome:  5
searching citobands in chromossome:  6
searching citobands in chromossome:  7
searching citobands in chromossome:  8
searching citobands in chromossome:  9
searching citobands in chromossome:  MT
searching citobands in chromossome:  X
searching citobands in chromossome:  Y


[array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0])]

In [16]:
introns_matrix = introns_exons_matrix(chromosmes, CDSs, exons)
introns_matrix

searching citobands in chromossome:  1
searching citobands in chromossome:  10
searching citobands in chromossome:  11
searching citobands in chromossome:  12
searching citobands in chromossome:  13
searching citobands in chromossome:  14
searching citobands in chromossome:  15
searching citobands in chromossome:  16
searching citobands in chromossome:  17
searching citobands in chromossome:  18
searching citobands in chromossome:  19
searching citobands in chromossome:  2
searching citobands in chromossome:  20
searching citobands in chromossome:  21
searching citobands in chromossome:  22
searching citobands in chromossome:  3
searching citobands in chromossome:  4
searching citobands in chromossome:  5
searching citobands in chromossome:  6
searching citobands in chromossome:  7
searching citobands in chromossome:  8
searching citobands in chromossome:  9
searching citobands in chromossome:  MT
searching citobands in chromossome:  X
searching citobands in chromossome:  Y


[array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0])]

In [17]:
#otherRegions_matrix = calc_group(chromosmes, regions)
#otherRegions_matrix

In [64]:
def calc_elementDensity(cytobands_df, element_matrix, col_name="Element_density"):
    #cytobands_df = cytobands_df.drop(cytobands_df[cytobands_df['Chromossome'] == 'chrM'].index)
    densities = []
    chromosomes = cytobands_df["Chromossome"].unique()
    for chrom in range(len(cytobands_df["Chromossome"].unique())):             
        chr_cytobands = cytobands_df.loc[cytobands_df['Chromossome'] == cytobands_df["Chromossome"].unique()[chrom]]
        print(chr_cytobands)
        #Calculo da densidade para cada cytoband
        for row in chr_cytobands.index:
            cytoband_array = element_matrix[chrom][int(chr_cytobands["First_index"][row]):int(chr_cytobands["Last_index"][row])]
            dr_length = np.count_nonzero(cytoband_array)
            cytoband_length = chr_cytobands["Size"][row]
            density = dr_length/cytoband_length
            densities.append(round(density, 3))
        
    cytobands_df.insert(len(cytobands_df.columns), col_name, densities, True)

In [19]:
cytoPath_read = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_processed_str_dr.txt"
cytoPath_write = "/home/androx/Documents/trabalho/citobands/cytobandFiltered_processed_str_dr_dg.txt"

cytobands_df = pd.read_csv(cytoPath_read, sep="\t")#, header=None))

cytobands_df

Chromossome  First_index  Last_index Citoband  Unkown      Size  \
0          chr1            0     2299999   p36.33    gneg   2299999   
1          chr1      2300000     5299999   p36.32  gpos25   2999999   
2          chr1      5300000     7099999   p36.31    gneg   1799999   
3          chr1      7100000     9099999   p36.23  gpos25   1999999   
4          chr1      9100000    12499999   p36.22    gneg   3399999   
..          ...          ...         ...      ...     ...       ...   
858        chrY     12400000    17099999  q11.221  gpos50   4699999   
859        chrY     17100000    19599999  q11.222    gneg   2499999   
860        chrY     19600000    23799999  q11.223  gpos50   4199999   
861        chrY     23800000    26599999   q11.23    gneg   2799999   
862        chrY     26600000    57227414      q12    gvar  30627414   

     STR_Density  DR_density  
0          0.088       0.326  
1          0.084       0.282  
2          0.056       0.275  
3          0.049       0.405  
4          0.056       0.404  
..           ...         ...  
858        0.037       0.015  
859        0.062       0.013  
860        0.082       0.006  
861        0.026       0.002  
862        0.006       0.001  

[863 rows x 8 columns]

In [65]:
calc_elementDensity(cytobands_df, exons_matrix, "Exons_density")
cytobands_df

   Chromossome  First_index  Last_index Citoband  Unkown     Size  \
0         chr1            0     2299999   p36.33    gneg  2299999   
1         chr1      2300000     5299999   p36.32  gpos25  2999999   
2         chr1      5300000     7099999   p36.31    gneg  1799999   
3         chr1      7100000     9099999   p36.23  gpos25  1999999   
4         chr1      9100000    12499999   p36.22    gneg  3399999   
..         ...          ...         ...      ...     ...      ...   
58        chr1    226800000   230499999   q42.13    gneg  3699999   
59        chr1    230500000   234599999    q42.2  gpos50  4099999   
60        chr1    234600000   236399999    q42.3    gneg  1799999   
61        chr1    236400000   243499999      q43  gpos75  7099999   
62        chr1    243500000   248956421      q44    gneg  5456421   

    STR_Density  DR_density  
0         0.088       0.326  
1         0.084       0.282  
2         0.056       0.275  
3         0.049       0.405  
4         0.056      

Chromossome  First_index  Last_index Citoband  Unkown      Size  \
0          chr1            0     2299999   p36.33    gneg   2299999   
1          chr1      2300000     5299999   p36.32  gpos25   2999999   
2          chr1      5300000     7099999   p36.31    gneg   1799999   
3          chr1      7100000     9099999   p36.23  gpos25   1999999   
4          chr1      9100000    12499999   p36.22    gneg   3399999   
..          ...          ...         ...      ...     ...       ...   
858        chrY     12400000    17099999  q11.221  gpos50   4699999   
859        chrY     17100000    19599999  q11.222    gneg   2499999   
860        chrY     19600000    23799999  q11.223  gpos50   4199999   
861        chrY     23800000    26599999   q11.23    gneg   2799999   
862        chrY     26600000    57227414      q12    gvar  30627414   

     STR_Density  DR_density  Exons_density  
0          0.088       0.326          0.171  
1          0.084       0.282          0.079  
2          0.056       0.275          0.082  
3          0.049       0.405          0.047  
4          0.056       0.404          0.093  
..           ...         ...            ...  
858        0.037       0.015          0.016  
859        0.062       0.013          0.045  
860        0.082       0.006          0.036  
861        0.026       0.002          0.034  
862        0.006       0.001          0.001  

[863 rows x 9 columns]